### ISSUE TITLE
Binary for macOS < 10.15?

### ISSUE THREAD

**Issue by fogoat** [prashantgupta24/automatic-mouse-mover#20]
I tried the binary but it says it wanted macOS 10.15. Do you have a binary for versions less than 10.15?

**Comment by prashantgupta24** [comment]
Hi @sunk818 , unfortunately I do not have access to a mac version earlier than that, I will try to find time to release one.

Meanwhile, have you tried installing from [source](https://github.com/prashantgupta24/automatic-mouse-mover#install-from-source)? It doesn't involve a lot of steps, let me know if that doesn't work!

**Comment by lucadip1** [comment]
Hi Prashant, I tried compiling the app from source but on my mac 10.13 it keeps prompting for accessibility rights for the app (which i enabled) and then it crashes.
Any idea?

**Comment by prashantgupta24** [comment]
Hey @lucadip1 , sorry to hear that. Any chance you can get the logs when it crashes? Maybe that will help.
