### ISSUE TITLE
Rename the executable

### ISSUE THREAD

**Issue by jorisw** [prashantgupta24/automatic-mouse-mover#23]
To me, amm.app is not very descriptive.

Proposal: Mouse Mover.app

**Comment by prashantgupta24** [comment]
Good suggestion. I will take it into consideration. Although instead of waiting for the renamed app, you can rename the app on your machine. It should be a one time step for you

**Comment by prashantgupta24** [comment]
Renaming the app will cause all users to reconfigure the Privacy options on Mac. Hence I chose not to rename the app officially. If anyone wants to rename the app, they can rename it locally on their machine.
