### ISSUE TITLE
Move mouse regadless of activity

### ISSUE THREAD

**Issue by bonarmada** [prashantgupta24/automatic-mouse-mover#31]
Could there be an option to move mouse after x minutes regardless if there is activity or none.

The cursor never moved causing the machine to sleep. My theory is that the app detects activity on the BG probably time tracker apps. 

Could this be a possible feature?

**Comment by prashantgupta24** [comment]
In your case, perhaps you can quit the app and reopen it, that might fix the cursor not moving issue.

**Comment by shanep2300** [comment]
I actually get the opposite to sometimes happen. It moves while I'm actively using the Mac. It also doesn't just move but also clicks. I can be typing and then my cursor just magically moves to another part of the type field.

**Comment by prashantgupta24** [comment]
@shanep2300 hmm, that has never happened to me. There is no clicking capability in the app, so not sure how that can happen. The only thing the app can do is to move the mouse cursor by a very small pixel amount

**Comment by shanep2300** [comment]
@prashantgupta24 You can ignore my request. I had other Automator scripts running that I completely forgot about it. Restarting my computer fixed the issue. Sorry about that...
