### ISSUE TITLE
amm keeps asking for Accessibility Access after upgrading from Catalina to Monetrey

### ISSUE THREAD

**Issue by dylankershaw** [prashantgupta24/automatic-mouse-mover#32]
amm used to work fine on my MacBook Pro (16-inch, 2019) but today I upgraded from Catalina to Monterey (v. 12.3.1) and now it won't stop prompting me for Accessibility Access:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/28968357/174173202-070652f5-bb59-450c-99ad-deb7b9dce54f.png">

I've already granted it access as you can see here:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/28968357/174174062-c9eeb926-f15f-4334-82a1-fd8889cb57bb.png">

I also restarted my computer, deleted and then reinstalled amm by redownloading the source from GitHub, but the problem persists. I am using amm v1.1.0.

**Comment by prashantgupta24** [comment]
Hmm, I'm also on mac OS Monterey (v12.4), and I'm also using v1.1.0, but I did not face this issue.

There are a lot of articles which suggest some fixes using the terminal when I google `accessibility access macos issue`, but I haven't tried them myself

**Comment by paoloestar** [comment]
try to remove amm with minus symbol and re-add it again. That fixed an issue with another app for me

**Comment by mrplug** [comment]
> try to remove amm with minus symbol and re-add it again. That fixed an issue with another app for me

This worked for me! :)

**Comment by ZachtimusPrime** [comment]
> try to remove amm with minus symbol and re-add it again. That fixed an issue with another app for me

This also worked for me, thank you.
