### ISSUE TITLE
Accessibility issue 

### ISSUE THREAD

**Issue by leoduth** [prashantgupta24/automatic-mouse-mover#38]
Hello, I tried to reinstall the application, remove the rights, put them back nothing changes it always gives me this message, someone has the same problem? 

On Ventura 13.0

<img width="471" alt="image" src="https://user-images.githubusercontent.com/58000981/205018306-e744cc9d-3d71-4f91-8bb0-046383f0f21f.png">

**Comment by prashantgupta24** [comment]
Possibly similar to this issue? https://github.com/prashantgupta24/automatic-mouse-mover/issues/32
