### ISSUE TITLE
[Feature] Install via Hombrew Cask

### ISSUE THREAD

**Issue by Resousse** [prashantgupta24/automatic-mouse-mover#46]
It would be great to install the latest release as an Hombrew Cask

**Comment by nihaals** [comment]
https://github.com/Homebrew/homebrew-cask/pull/162449

**Comment by prashantgupta24** [comment]
```
    Please contact the upstream developer to let them know they should sign and notarize their software.
```

😢

**Comment by prashantgupta24** [comment]
Thanks for the effort @nihaals !

**Comment by nihaals** [comment]
Unless the app becomes signed or someone makes a tap (probables makes sense for it to be official), this issue might make sense to close.
