### ISSUE TITLE
Access problem with macOS 14.1.1

### ISSUE THREAD

**Issue by Fr3d3rick83** [prashantgupta24/automatic-mouse-mover#55]
Hi, every time when I start the app, I´ll get this message. Than every time the app would start moving the mouse, I´ll recieve this message again.

Its the lates versin of macOS and amm.

![Bildschirmfoto 2023-11-22 um 07 03 00](https://github.com/prashantgupta24/automatic-mouse-mover/assets/97901424/bbe25ba8-f083-46fd-a861-741ae99a2ef8)

**Comment by prashantgupta24** [comment]
Hi @Fr3d3rick83 , have you allowed the necessary permissions? Once you do that, this window will not come again

**Comment by Fr3d3rick83** [comment]
Thats the problem, it apears all the time, the permission is allowed.

**Comment by CasparWaara** [comment]
Same problem here. os 14.1.1. and amm 1.3.0

**Comment by Fr3d3rick83** [comment]
Just a quick example:
https://github.com/prashantgupta24/automatic-mouse-mover/assets/97901424/138284a8-bc4f-4919-9d20-31fa070d5479

**Comment by prashantgupta24** [comment]
@Fr3d3rick83 try removing the app (the `-` sign at the bottom left), then adding the app again. That always works for me

**Comment by Fr3d3rick83** [comment]
Thanks, that worked
