### ISSUE TITLE
Why is the support for macOS Monterey dropped?

### ISSUE THREAD

**Issue by danielrichter78** [prashantgupta24/automatic-mouse-mover#57]
Hello,

i use it on an older macbook pro. why is the new version only usable under 13.0?

<img width="409" alt="Bildschirmfoto 2023-12-15 um 10 38 52" src="https://github.com/prashantgupta24/automatic-mouse-mover/assets/10697840/49555920-1000-4dda-90e5-1acc613fc32e">

**Comment by prashantgupta24** [comment]
Oh I never realized that happened, that's weird 🤔

**Comment by kholis** [comment]
Me too. I have macOS 11.6.6 and failed to run the binary. Please support older version of macOS.

**Comment by Salman-EF** [comment]
Same here with `Monterey 12.7.2` when trying to install & run from binary but after [installing from source](https://github.com/prashantgupta24/automatic-mouse-mover?tab=readme-ov-file#install-from-source) it runs as expected.

**Comment by prashantgupta24** [comment]
Thanks @Salman-EF ! Closing this issue, installing from source as mentioned above is the expected way for installing for older mac versions
