### ISSUE TITLE
Issue with Privacy and Security

### ISSUE THREAD

**Issue by jeremyfranklin** [prashantgupta24/automatic-mouse-mover#60]
Anyone having issues with privacy and security accessibility settings.  It says it is allowed in the Privacy and Security settings, but I keep get warnings like it is not and then it won't run.  I am on Sonoma 14.5.

**Comment by prashantgupta24** [comment]
I'm on Sonoma 14.5 too, I don't see this problem. Are you sure you quit the app and restart it after granting permissions? Also worth trying a full restart? Apologies for dumb suggestions but can't really think of anything else...

**Comment by danielrichter78** [comment]
I am on Sonoma 14.6 and i have the same problem, on every start the dialog come:
![Bildschirmfoto 2024-08-07 um 07 22 33](https://github.com/user-attachments/assets/8add43ce-f259-4fd6-9aac-1c7bcf2ff2e1)

**Comment by danielrichter78** [comment]
> I'm on Sonoma 14.5 too, I don't see this problem. Are you sure you quit the app and restart it after granting permissions? Also worth trying a full restart? Apologies for dumb suggestions but can't really think of anything else...

a full restart does not help ... only the version 1.2 works

**Comment by danielrichter78** [comment]
When i delete the app in the privacy settings, then i open the amm.app again and activate it in the settings, then the problem is gone. Tested with 14.6.1

**Comment by prashantgupta24** [comment]
> When i delete the app in the privacy settings, then i open the amm.app again and activate it in the settings, then the problem is gone. Tested with 14.6.1

Alright, looks like we have a solution! Going to close this for now.

@danielrichter78 I have rarely seen the app crash but it's certainly possible that's what happened. You can try to find more information in system logs, otherwise you can try to run it via script if it happens frequently as mentioned here: https://github.com/prashantgupta24/automatic-mouse-mover/issues/47#issuecomment-1747308387

**Comment by danielrichter78** [comment]
> > When i delete the app in the privacy settings, then i open the amm.app again and activate it in the settings, then the problem is gone. Tested with 14.6.1
> 
> Alright, looks like we have a solution! Going to close this for now.
> 
> @danielrichter78 I have rarely seen the app crash but it's certainly possible that's what happened. You can try to find more information in system logs, otherwise you can try to run it via script if it happens frequently as mentioned here: [#47 (comment)](https://github.com/prashantgupta24/automatic-mouse-mover/issues/47#issuecomment-1747308387)

Do you have an argument to start in terminal with logs? Perhaps like for Google Chrome:

Alternatively if your application has debug or verbosity flags, you can pass the flag to your application using open --args. For example, Google Chrome has the flags --enable-logging --v=1 to turn on debugging and save the output to chrome_debug.log in the Chrome user data directory. You can launch Google Chrome with the following options

open -a "Google Chrome" --args --enable-logging --v=1
